[log]
  # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
  level = "DEBUG" # Should change this after setup

[api]
  dashboard = true
  debug = true
  insecure = true # If true, you can access dashboard on 8080 port (open 8080 first..)

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false # traefik.enable=true is needed
  network = "app-net"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
  
[ping]
  entryPoint = "web"

[http]
  [http.routers]
     # Define a connection between requests and services
     [http.routers.to-dashboard]
      rule = "Host(`traefik.${DOMAINNAME}`)"
      service = "traefik"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "domain.tld"
  watch = true
  exposedbydefault = false

[acme]
  email = "emailForLetsEncryptACME"
  storage = "acme.json"
  storageFile = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  OnHostRule = true
  [acme.tlsChallenge]
  [[acme.domains]]
    main = "pihole.pi.lan"
  [[acme.domains]]
   main = "pi.lan"
  [[acme.domains]]
    main = "*.pi.lan"